services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tonsinn\BelegungsplanBundle\:
        resource: '../../*'
        exclude: '../../{Resources,DependencyInjection,TonsinnBelegungsplanBundle.php}'
